# View all Tables
SELECT table_name FROM all_tables WHERE owner='DIVYA';


set define off;

# Create Employee
CREATE TABLE employee ( 
	employee_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(employee_id),
	first_name VARCHAR(40) NOT NULL, 
	last_name VARCHAR(40) NOT NULL, 
	email VARCHAR(60) NOT NULL,
	password VARCHAR(60) NOT NULL,
	address VARCHAR(70),
	city VARCHAR(40), 
	state VARCHAR(40), 
	postal_code VARCHAR(10), 
	country VARCHAR(40), 
	phone_no NUMBER(30), 
	date_of_birth DATE,
	role VARCHAR(40) );
	 
	 
# Create Customer
CREATE TABLE customer ( 
	customer_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(customer_id),
	first_name VARCHAR(40) NOT NULL, 
	last_name VARCHAR(40) NOT NULL, 
	email VARCHAR(60) NOT NULL,
	password VARCHAR(60) NOT NULL,
	address VARCHAR(70),
	city VARCHAR(40), 
	state VARCHAR(40), 
	postal_code VARCHAR(10), 
	country VARCHAR(40), 
	credit_card_type VARCHAR(24), 
	credit_card_no NUMBER(30), 
	credit_card_expiration_date DATE
	 );
	 
# Create Band
CREATE TABLE band ( 
	band_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(band_id),
	name VARCHAR(120) NOT NULL,
	password VARCHAR(60) NOT NULL,
	band_members VARCHAR(120),
	description LONG);
	
# Create Genre
CREATE TABLE genre (
	genre_id NUMBER(2) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(genre_id),
	genre_name VARCHAR(60) NOT NULL);
	 
# Create recordtype
CREATE TABLE record_type (
	record_type_id NUMBER(2) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(record_type_id),
	record_type_name VARCHAR(60) NOT NULL,
	duration NUMBER(5));
	
# Create Status
CREATE TABLE status (
	status_id NUMBER(2) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(status_id),
	status_name VARCHAR(60) NOT NULL,
	type VARCHAR(60) NOT NULL);
	
# Create Invoice
CREATE TABLE invoice ( 
	invoice_id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(invoice_id),
	customer_id NUMBER(5) NOT NULL, 
	invoice_date DATE, 
	status_id NUMBER(2),
	total_price NUMBER(10,2), 
	employee_id NUMBER(5),
	FOREIGN KEY (customer_id) REFERENCES customer,
	FOREIGN KEY (status_id) REFERENCES status,
	FOREIGN KEY (employee_id) REFERENCES employee);
	
# Create track
CREATE TABLE track ( 
		track_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
		PRIMARY KEY(track_id),
		track_name VARCHAR(160) NOT NULL, 
		genre_id NUMBER(2) NOT NULL, 
		url VARCHAR(160) NOT NULL, 
		duration NUMBER (5,2) NOT NULL, 
		price NUMBER (10,2) NOT NULL, 
		band_id INTEGER NOT NULL,
		FOREIGN KEY (genre_id) REFERENCES genre,
		FOREIGN KEY (band_id) REFERENCES band);
		
# Create Record
CREATE TABLE record ( 
		record_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY, 
		PRIMARY KEY(record_id),
		duration NUMBER (5,2) NOT NULL, 
		price NUMBER(10,2) NOT NULL, 
		record_type_id NUMBER(2),
		invoice_id NUMBER(20),
		status_id NUMBER(2),
		FOREIGN KEY (record_type_id) REFERENCES record_type,
		FOREIGN KEY (status_id) REFERENCES status,
		FOREIGN KEY (invoice_id) REFERENCES invoice);
	
# Create RecordTrack
CREATE TABLE record_track ( 
	record_track_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	PRIMARY KEY(record_track_id),
	record_id NUMBER(5) NOT NULL, 
	track_id NUMBER(5) NOT NULL, 
	added NUMBER(1) DEFAULT 0,
	FOREIGN KEY (record_id) REFERENCES record,
	FOREIGN KEY (track_id) REFERENCES track  );
	
# Trigger to update record price	
CREATE OR REPLACE TRIGGER update_record_price
	AFTER INSERT OR DELETE ON record_track
	FOR EACH ROW
DECLARE 
	old_price NUMBER(10,2);
	new_price NUMBER(10,2);
BEGIN
	Select price into old_price from record where record_id = :NEW.record_id;	
	Select price into new_price from track where track_id = :NEW.track_id;
	UPDATE record SET price = 	old_price + new_price WHERE record_id = :NEW.record_id;	
END;
/
	
ALTER TRIGGER update_record_price DISABLE;
ALTER TRIGGER update_record_price ENABLE;

BEGIN
	FOR rec in (SELECT UNIQUE record_id FROM record_track)
    LOOP
    	UPDATE record
   		SET duration = (SELECT sum(duration) FROM track t, record_track rt WHERE t.track_id = rt.track_id and rt.record_id= rec.record_id)
   		WHERE record_id = rec.record_id;
    END LOOP;      
    COMMIT;
END;
/


BEGIN
	FOR rec in (SELECT UNIQUE invoice_id FROM record)
    LOOP
    	UPDATE invoice
   		SET total_price = (SELECT sum(price) FROM record WHERE invoice_id= rec.invoice_id)
   		WHERE invoice_id = rec.invoice_id;
    END LOOP;      
    COMMIT;
END;
/

INSERT INTO customer VALUES (NULL,'Luis','Goncalves','luisg@embraer.com.br','luisg','Av. Brigadeiro Faria Lima 2170','São José dos Campos','SP','12227-000','Brazil','Discover',65245320164465,TO_DATE('11/9/2032', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Leonie','Kohler','leonekohler@surfeu.de','leonekohler','Theodor-Heuss-Straße 34','Stuttgart','None','70174','Germany','Discover',35887550616907,TO_DATE('8/3/2026', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Francois','Tremblay','ftremblay@gmail.com','ftremblay','1498 rue Bélanger','Montréal','QC','H2G 1A7','Canada','Discover',78499923680572,TO_DATE('7/18/2032', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Bjorn','Hansen','bjorn.hansen@yahoo.no','bjorn.hansen','Ullevålsveien 14','Oslo','None','0171','Norway','Mastercard',65396642491925,TO_DATE('10/8/2027', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Frantisek','Wichterlova','frantisekw@jetbrains.com','frantisekw','Klanova 9/506','Prague','None','14700','Czech Republic','Mastercard',68256657180070,TO_DATE('1/2/2026', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Helena','Holy','hholy@gmail.com','hholy','Rilská 3174/6','Prague','None','14300','Czech Republic','Discover',41741633408899,TO_DATE('11/9/2032', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Astrid','Gruber','astrid.gruber@apple.at','astrid.gruber','Rotenturmstraße 4 1010 Innere Stadt','Vienne','None','1010','Austria','Visa',40891267514067,TO_DATE('11/13/2030', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Daan','Peeters','daan_peeters@apple.be','daan_peeters','Grétrystraat 63','Brussels','None','1000','Belgium','American Express',41897111873332,TO_DATE('5/16/2028', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Kara','Nielsen','kara.nielsen@jubii.dk','kara.nielsen','Sønder Boulevard 51','Copenhagen','None','1720','Denmark','Visa',82667052659952,TO_DATE('4/24/2031', 'mm/dd/yyyy'));
INSERT INTO customer VALUES (NULL,'Eduardo','Martins','eduardo@woodstock.com.br','eduardo','Rua Dr. Falcão Filho 155','São Paulo','SP','01007-010','Brazil','Visa',95360911274647,TO_DATE('11/21/2034', 'mm/dd/yyyy'));

INSERT INTO employee VALUES (NULL,'Andrew','Adams','andrew@chinookcorp.com','andrew','11120 Jasper Ave NW','Edmonton','AB','T5K 2N1','Canada',5455701990,TO_DATE('4/14/1980', 'mm/dd/yyyy'), 'Employee');
INSERT INTO employee VALUES (NULL,'Nancy','Edwards','nancy@chinookcorp.com','nancy','825 8 Ave SW','Calgary','AB','T2P 2T3','Canada',2607118163,TO_DATE('11/10/1997', 'mm/dd/yyyy'), 'Employee');
INSERT INTO employee VALUES (NULL,'Jane','Peacock','jane@chinookcorp.com','jane','1111 6 Ave SW','Calgary','AB','T2P 5M5','Canada',6235050964,TO_DATE('9/18/1997', 'mm/dd/yyyy'), 'Employee');
INSERT INTO employee VALUES (NULL,'Margaret','Park','margaret@chinookcorp.com','margaret','683 10 Street SW','Calgary','AB','T2P 5G3','Canada',7729123847,TO_DATE('9/7/1991', 'mm/dd/yyyy'), 'Employee');
INSERT INTO employee VALUES (NULL,'Steve','Johnson','steve@chinookcorp.com','steve','7727B 41 Ave','Calgary','AB','T3B 1Y7','Canada',3040172834,TO_DATE('3/12/1975', 'mm/dd/yyyy'), 'Employee');
INSERT INTO employee VALUES (NULL,'Michael','Mitchell','michael@chinookcorp.com','michael','5827 Bowness Road NW','Calgary','AB','T3B 0C5','Canada',4934712761,TO_DATE('7/13/1970', 'mm/dd/yyyy'), 'Employee');
INSERT INTO employee VALUES (NULL,'Robert','King','robert@chinookcorp.com','robert','590 Columbia Boulevard West','Lethbridge','AB','T1K 5N8','Canada',4121388548,TO_DATE('2/9/1981', 'mm/dd/yyyy'), 'Employee');
INSERT INTO employee VALUES (NULL,'Laura','Callahan','laura@chinookcorp.com','laura','923 7 ST NW','Lethbridge','AB','T1H 1Y8','Canada',2563146227,TO_DATE('10/2/1994', 'mm/dd/yyyy'), 'Employee');

INSERT INTO band VALUES (NULL,'AC/DC','AC/DC','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'Aerosmith','Aerosmith','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'The Beatles','The Beatles','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'Queen','Queen','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'Chainsmokers','Chainsmokers','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'Linkin Park','Linkin Park','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'Pink Floyd','Pink Floyd','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'Backstreet Boys','Backstreet Boys','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'One Direction','One Direction','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');
INSERT INTO band VALUES (NULL,'Maroon5','Maroon5','band member 1,band member 2,band member 3,band member 4, band member 5','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed turpis enim.');

INSERT INTO genre VALUES (NULL,'Rock');
INSERT INTO genre VALUES (NULL,'Jazz');
INSERT INTO genre VALUES (NULL,'Metal');
INSERT INTO genre VALUES (NULL,'Alternative & Punk');
INSERT INTO genre VALUES (NULL,'Rock And Roll');
INSERT INTO genre VALUES (NULL,'Blues');
INSERT INTO genre VALUES (NULL,'Latin');
INSERT INTO genre VALUES (NULL,'Reggae');
INSERT INTO genre VALUES (NULL,'Pop');
INSERT INTO genre VALUES (NULL,'Soundtrack');
INSERT INTO genre VALUES (NULL,'Bossa Nova');
INSERT INTO genre VALUES (NULL,'Easy Listening');
INSERT INTO genre VALUES (NULL,'Heavy Metal');
INSERT INTO genre VALUES (NULL,'R&B/Soul');
INSERT INTO genre VALUES (NULL,'Electronica/Dance');
INSERT INTO genre VALUES (NULL,'World');
INSERT INTO genre VALUES (NULL,'Hip Hop/Rap');
INSERT INTO genre VALUES (NULL,'Science Fiction');
INSERT INTO genre VALUES (NULL,'TV Shows');
INSERT INTO genre VALUES (NULL,'Sci Fi & Fantasy');
INSERT INTO genre VALUES (NULL,'Drama');
INSERT INTO genre VALUES (NULL,'Comedy');
INSERT INTO genre VALUES (NULL,'Alternative');
INSERT INTO genre VALUES (NULL,'Classical');
INSERT INTO genre VALUES (NULL,'Opera');

INSERT INTO record_type VALUES (NULL,'Long-Playing Vinyl Records (L.P.)',18);
INSERT INTO record_type VALUES (NULL,'Extended Play Vinyl Records (E.P.)',30);

INSERT INTO status VALUES (NULL,'New');
INSERT INTO status VALUES (NULL,'Ordered');
INSERT INTO status VALUES (NULL,'In Progress');
INSERT INTO status VALUES (NULL,'Out for Delivery');
INSERT INTO status VALUES (NULL,'Delivered');
INSERT INTO status VALUES (NULL,'RecordNew');
INSERT INTO status VALUES (NULL,'RecordComplete');

INSERT INTO track VALUES (NULL,'Thunderstruck',6,'track_folder/1/thunderstruck.mp3',1.11,2.41,1);
INSERT INTO track VALUES (NULL,'Highway to Hell',24,'track_folder/1/highway to hell.mp3',2.5,7.06,1);
INSERT INTO track VALUES (NULL,'Back In Black',7,'track_folder/1/back in black.mp3',4.27,7.77,1);
INSERT INTO track VALUES (NULL,'you shook me all night long',20,'track_folder/1/you shook me all night long.mp3',2.61,4.35,1);
INSERT INTO track VALUES (NULL,'Let There Be Rock',16,'track_folder/1/let there be rock.mp3',3.09,8.63,1);
INSERT INTO track VALUES (NULL,'Shoot to Thrill',3,'track_folder/1/shoot to thrill.mp3',1.93,0.51,1);
INSERT INTO track VALUES (NULL,'Hells Bells',20,'track_folder/1/hells bells.mp3',3.11,5.0,1);
INSERT INTO track VALUES (NULL,'Whole Lotta Rosie',6,'track_folder/1/whole lotta rosie.mp3',4.95,2.27,1);
INSERT INTO track VALUES (NULL,'dirty deeds done dirt cheap',15,'track_folder/1/dirty deeds done dirt cheap.mp3',3.06,4.37,1);
INSERT INTO track VALUES (NULL,'Shot in the Dark',22,'track_folder/1/shot in the dark.mp3',1.71,4.95,1);
INSERT INTO track VALUES (NULL,'What It Takes',23,'track_folder/2/what it takes.mp3',4.92,1.97,2);
INSERT INTO track VALUES (NULL,'Last Child',5,'track_folder/2/last child.mp3',4.48,7.45,2);
INSERT INTO track VALUES (NULL,'Mama Kin',24,'track_folder/2/mama kin.mp3',1.0,7.3,2);
INSERT INTO track VALUES (NULL,'Back in the Saddle',6,'track_folder/2/back in the saddle.mp3',4.63,3.55,2);
INSERT INTO track VALUES (NULL,'I Dont Want to Miss a Thing',20,'track_folder/2/i dont want to miss a thing.mp3',3.46,3.47,2);
INSERT INTO track VALUES (NULL,'Dude (Looks Like a Lady)',12,'track_folder/2/dude (looks like a lady).mp3',4.61,4.95,2);
INSERT INTO track VALUES (NULL,'Janies Got a Gun',2,'track_folder/2/janies got a gun.mp3',1.61,6.23,2);
INSERT INTO track VALUES (NULL,'Sweet Emotion',24,'track_folder/2/sweet emotion.mp3',3.85,5.4,2);
INSERT INTO track VALUES (NULL,'Dream On',12,'track_folder/2/dream on.mp3',3.17,0.39,2);
// INSERT INTO track VALUES (NULL,'Walk This Way',7,'track_folder/2/walk this way.mp3',2.1 5,8.64,2);
INSERT INTO track VALUES (NULL,'While My Guitar Gently Weeps',20,'track_folder/3/while my guitar gently weeps.mp3',3.74,1.87,3);
INSERT INTO track VALUES (NULL,'A Day in the Life',11,'track_folder/3/a day in the life.mp3',1.29,8.12,3);
INSERT INTO track VALUES (NULL,'I Want to Hold Your Hand',18,'track_folder/3/i want to hold your hand.mp3',4.06,5.23,3);
INSERT INTO track VALUES (NULL,'Strawberry Fields Forever',5,'track_folder/3/strawberry fields forever.mp3',2.63,9.66,3);
INSERT INTO track VALUES (NULL,'Yesterday',16,'track_folder/3/yesterday.mp3',1.61,5.86,3);
INSERT INTO track VALUES (NULL,'In My Life',12,'track_folder/3/in my life.mp3',3.03,2.71,3);
INSERT INTO track VALUES (NULL,'Something',10,'track_folder/3/something.mp3',1.42,6.81,3);
INSERT INTO track VALUES (NULL,'Hey Jude',19,'track_folder/3/hey jude.mp3',3.47,0.92,3);
INSERT INTO track VALUES (NULL,'Let It Be',11,'track_folder/3/let it be.mp3',2.41,1.62,3);
INSERT INTO track VALUES (NULL,'Come Together',8,'track_folder/3/come together .mp3',1.75,6.15,3);
INSERT INTO track VALUES (NULL,'I Want to Break Free',2,'track_folder/4/i want to break free.mp3',2.83,7.25,4);
INSERT INTO track VALUES (NULL,'Killer Queen',13,'track_folder/4/killer queen.mp3',4.11,4.47,4);
INSERT INTO track VALUES (NULL,'The Show Must Go On',7,'track_folder/4/the show must go on.mp3',1.99,9.72,4);
INSERT INTO track VALUES (NULL,'Under Pressure',1,'track_folder/4/under pressure.mp3',1.13,4.01,4);
INSERT INTO track VALUES (NULL,'Crazy Little Thing Called Love',12,'track_folder/4/crazy little thing called love.mp3',3.3,7.99,4);
INSERT INTO track VALUES (NULL,'Who Wants to Live Forever',21,'track_folder/4/who wants to live forever.mp3',4.02,3.09,4);
INSERT INTO track VALUES (NULL,'Somebody to Love',10,'track_folder/4/somebody to love.mp3',2.16,2.28,4);
INSERT INTO track VALUES (NULL,'Dont Stop Me Now',2,'track_folder/4/dont stop me now.mp3',3.17,0.05,4);
INSERT INTO track VALUES (NULL,'Fat Bottomed Girls',25,'track_folder/4/fat bottomed girls.mp3',3.28,9.71,4);
INSERT INTO track VALUES (NULL,'Bohemian Rhapsody',24,'track_folder/4/bohemian rhapsody.mp3',3.95,3.88,4);
INSERT INTO track VALUES (NULL,'Something Just Like This',10,'track_folder/5/something just like this.mp3',4.27,2.25,5);
INSERT INTO track VALUES (NULL,'Closer',6,'track_folder/5/closer.mp3',3.74,2.75,5);
INSERT INTO track VALUES (NULL,'Dont Let Me Down',18,'track_folder/5/dont let me down.mp3',4.16,2.08,5);
INSERT INTO track VALUES (NULL,'Paris',4,'track_folder/5/paris.mp3',2.44,4.9,5);
INSERT INTO track VALUES (NULL,'Roses',11,'track_folder/5/roses.mp3',4.47,2.24,5);
INSERT INTO track VALUES (NULL,'Takeaway',2,'track_folder/5/takeaway.mp3',2.87,4.28,5);
INSERT INTO track VALUES (NULL,'This Feeling',22,'track_folder/5/this feeling.mp3',2.48,8.48,5);
INSERT INTO track VALUES (NULL,'Call You Mine',22,'track_folder/5/call you mine.mp3',2.41,5.64,5);
INSERT INTO track VALUES (NULL,'High',9,'track_folder/5/high.mp3',2.02,0.97,5);
INSERT INTO track VALUES (NULL,'All We Know',3,'track_folder/5/all we know.mp3',2.1,7.43,5);
INSERT INTO track VALUES (NULL,'A Place for My Head',16,'track_folder/6/a place for my head.mp3',1.18,7.14,6);
INSERT INTO track VALUES (NULL,'Crawling',19,'track_folder/6/crawling.mp3',1.07,1.28,6);
INSERT INTO track VALUES (NULL,'Waiting for the End',19,'track_folder/6/waiting for the end.mp3',1.27,1.72,6);
INSERT INTO track VALUES (NULL,'One Step Closer',16,'track_folder/6/one step closer.mp3',3.3,7.86,6);
INSERT INTO track VALUES (NULL,'Somewhere I Belong',19,'track_folder/6/somewhere i belong.mp3',2.93,7.91,6);
INSERT INTO track VALUES (NULL,'Breaking the Habit',17,'track_folder/6/breaking the habit.mp3',2.28,5.83,6);
INSERT INTO track VALUES (NULL,'Faint',22,'track_folder/6/faint.mp3',2.5,6.09,6);
INSERT INTO track VALUES (NULL,'Papercut',13,'track_folder/6/papercut.mp3',3.18,2.24,6);
INSERT INTO track VALUES (NULL,'Numb',10,'track_folder/6/numb.mp3',1.7,8.28,6);
INSERT INTO track VALUES (NULL,'In the End',19,'track_folder/6/in the end.mp3',2.82,5.84,6);
INSERT INTO track VALUES (NULL,'Hey You',19,'track_folder/7/hey you.mp3',1.28,5.53,7);
INSERT INTO track VALUES (NULL,'Dogs',18,'track_folder/7/dogs.mp3',1.34,4.66,7);
INSERT INTO track VALUES (NULL,'Us & Them',1,'track_folder/7/us & them.mp3',3.58,1.49,7);
INSERT INTO track VALUES (NULL,'Another Brick In The Wall (Part 2)',16,'track_folder/7/another brick in the wall (part 2).mp3',2.46,8.05,7);
INSERT INTO track VALUES (NULL,'Money',8,'track_folder/7/money.mp3',3.12,1.76,7);
INSERT INTO track VALUES (NULL,'Echoes',19,'track_folder/7/echoes.mp3',4.29,6.11,7);
INSERT INTO track VALUES (NULL,'Shine On You Crazy Diamond',9,'track_folder/7/shine on you crazy diamond.mp3',3.79,2.81,7);
INSERT INTO track VALUES (NULL,'Time',25,'track_folder/7/time.mp3',1.55,2.12,7);
INSERT INTO track VALUES (NULL,'Comfortably Numb',2,'track_folder/7/comfortably numb.mp3',2.62,7.95,7);
INSERT INTO track VALUES (NULL,'Wish You Were Here',24,'track_folder/7/wish you were here.mp3',3.59,3.77,7);
// INSERT INTO track VALUES (NULL,'Show Me The Meaning Of Being Lonely',21,'track_folder/8/show me the meaning of being lonely.mp3',1.36,0.7SP2-0734: ,8);
INSERT INTO track VALUES (NULL,'More Than That',18,'track_folder/8/more than that.mp3',2.73,8.15,8);
INSERT INTO track VALUES (NULL,'Don’t Go Breaking My Heart',19,'track_folder/8/don’t go breaking my heart.mp3',3.79,2.41,8);
INSERT INTO track VALUES (NULL,'Quit Playing Games With My Heart',10,'track_folder/8/quit playing games with my heart.mp3',4.71,4.29,8);
INSERT INTO track VALUES (NULL,'As Long As You Love Me',19,'track_folder/8/as long as you love me.mp3',4.28,2.81,8);
INSERT INTO track VALUES (NULL,'Everybody',16,'track_folder/8/everybody.mp3',2.93,6.69,8);
INSERT INTO track VALUES (NULL,'I Want It That Way',6,'track_folder/8/i want it that way.mp3',3.43,9.36,8);
INSERT INTO track VALUES (NULL,'Larger Than Life',21,'track_folder/8/larger than life.mp3',3.04,2.94,8);
INSERT INTO track VALUES (NULL,'Shape Of My Heart',2,'track_folder/8/shape of my heart.mp3',4.99,9.14,8);
INSERT INTO track VALUES (NULL,'We ve Got It Going On',25,'track_folder/8/we ve got it going on.mp3',1.53,4.72,8);
INSERT INTO track VALUES (NULL,'Little White Lies',7,'track_folder/9/little white lies.mp3',2.27,6.33,9);
INSERT INTO track VALUES (NULL,'Night Changes',21,'track_folder/9/night changes.mp3',2.49,8.44,9);
INSERT INTO track VALUES (NULL,'History',24,'track_folder/9/history.mp3',1.8,3.49,9);
INSERT INTO track VALUES (NULL,'Change Your Ticket',15,'track_folder/9/change your ticket.mp3',1.21,9.51,9);
INSERT INTO track VALUES (NULL,'Long Way Down',21,'track_folder/9/long way down.mp3',1.22,7.05,9);
INSERT INTO track VALUES (NULL,'Stockholm Syndrome',3,'track_folder/9/stockholm syndrome.mp3',3.17,1.82,9);
INSERT INTO track VALUES (NULL,'Perfect',3,'track_folder/9/perfect.mp3',1.19,5.19,9);
INSERT INTO track VALUES (NULL,'Once in a Lifetime',4,'track_folder/9/once in a lifetime.mp3',3.87,6.85,9);
INSERT INTO track VALUES (NULL,'What Makes You Beautiful',17,'track_folder/9/what makes you beautiful.mp3' ,2.61,1.84,9);
INSERT INTO track VALUES (NULL,'Shes Not Afraid',20,'track_folder/9/shes not afraid.mp3',1.74,7.08,9);
INSERT INTO track VALUES (NULL,'Won’t Go Home Without You',20,'track_folder/10/won’t go home without you.mp3',1.06,6.5,10);
INSERT INTO track VALUES (NULL,'Girls Like You feat. Cardi B',12,'track_folder/10/girls like you feat. cardi b.mp3',1.78,9.1,10);
INSERT INTO track VALUES (NULL,'Sugar',17,'track_folder/10/sugar.mp3',3.45,0.92,10);
INSERT INTO track VALUES (NULL,'One More Night',22,'track_folder/10/one more night.mp3',3.54,9.26,10);
INSERT INTO track VALUES (NULL,'Cold feat. Future',12,'track_folder/10/cold feat. future.mp3',2.73,9.74,10);
INSERT INTO track VALUES (NULL,'She Will Be Loved',9,'track_folder/10/she will be loved.mp3',2.7,9.26,10);
INSERT INTO track VALUES (NULL,'Maps',2,'track_folder/10/maps.mp3',4.63,8.86,10);
INSERT INTO track VALUES (NULL,'Moves Like Jagger feat. Christina Aguilera',2,'track_folder/10/moves like jagger feat. christina aguilera.mp3',1.6,3.72,10);
INSERT INTO track VALUES (NULL,'This Love',5,'track_folder/10/this love.mp3',1.84,0.49,10);
INSERT INTO track VALUES (NULL,'Makes Me Wonder',12,'track_folder/10/makes me wonder.mp3',2.5,0.41,10);

INSERT INTO invoice VALUES (NULL,7,TO_DATE('12/14/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,3,TO_DATE('10/15/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,2,TO_DATE('9/16/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,1,TO_DATE('4/7/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,9,TO_DATE('4/12/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,5,TO_DATE('4/8/2018', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,2,TO_DATE('5/20/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,9,TO_DATE('1/3/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,6,TO_DATE('7/6/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('12/27/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,5,TO_DATE('9/3/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,5,TO_DATE('11/24/2018', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,9,TO_DATE('3/10/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,6,TO_DATE('11/4/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,2,TO_DATE('8/1/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,8,TO_DATE('6/25/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('12/4/2018', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,9,TO_DATE('8/7/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,7,TO_DATE('5/25/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,5,TO_DATE('7/26/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,3,TO_DATE('1/27/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('12/27/2019', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,7,TO_DATE('6/17/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,5,TO_DATE('8/6/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,8,TO_DATE('5/1/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,9,TO_DATE('1/16/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,3,TO_DATE('8/24/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,1,TO_DATE('3/13/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,6,TO_DATE('3/9/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,1,TO_DATE('11/27/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,4,TO_DATE('5/1/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,8,TO_DATE('1/18/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('7/28/2018', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,2,TO_DATE('12/23/2018', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,1,TO_DATE('7/17/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,7,TO_DATE('11/16/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,8,TO_DATE('2/18/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,1,TO_DATE('10/27/2018', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('9/5/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,2,TO_DATE('2/21/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,6,TO_DATE('12/21/2022', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('7/19/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,8,TO_DATE('12/2/2020', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('5/4/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,3,TO_DATE('6/12/2019', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,10,TO_DATE('5/4/2018', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,4,TO_DATE('6/3/2021', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,6,TO_DATE('1/2/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,7,TO_DATE('4/14/2023', 'mm/dd/yyyy'),1,0.00, NULL);
INSERT INTO invoice VALUES (NULL,1,TO_DATE('9/24/2022', 'mm/dd/yyyy'),1,0.00, NULL);

INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 35,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 29,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 10,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 37,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 23,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 2,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 11,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 28,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 26,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 39,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 2,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 41,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 46,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 7,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 21,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 42,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 14,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 41,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 46,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 9,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 46,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 31,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 11,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 46,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 8,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 15,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 24,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 25,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 33,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 20,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 35,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 50,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 37,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 33,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 6,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 27,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 40,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 6,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 41,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 44,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 27,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 4,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 17,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 18,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 46,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 18,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 34,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 28,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 40,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 20,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 36,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 33,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 41,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 47,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 2,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 28,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 40,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 31,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 9,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 11,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 14,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 40,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 1,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 13,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 7,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 5,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 45,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 12,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 45,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 28,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 31,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 20,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 2,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 2,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 26,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 21,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 50,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 45,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 45,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 7,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 38,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 10,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 38,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 31,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 31,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 20,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 17,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 29,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 21,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 33,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 3,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 10,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 10,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 21,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 38,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 44,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,2, 5,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 8,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 23,6);
INSERT INTO record VALUES (NULL, 0.00, 0.00,1, 18,6);

INSERT INTO record_track VALUES (NULL,78,19,1);
INSERT INTO record_track VALUES (NULL,47,46,0);
INSERT INTO record_track VALUES (NULL,29,30,0);
INSERT INTO record_track VALUES (NULL,87,70,0);
INSERT INTO record_track VALUES (NULL,47,59,1);
INSERT INTO record_track VALUES (NULL,33,23,1);
INSERT INTO record_track VALUES (NULL,16,19,0);
INSERT INTO record_track VALUES (NULL,54,11,1);
INSERT INTO record_track VALUES (NULL,72,72,1);
INSERT INTO record_track VALUES (NULL,66,30,0);
INSERT INTO record_track VALUES (NULL,81,2,1);
INSERT INTO record_track VALUES (NULL,65,61,0);
INSERT INTO record_track VALUES (NULL,12,12,0);
INSERT INTO record_track VALUES (NULL,18,87,1);
INSERT INTO record_track VALUES (NULL,50,68,1);
INSERT INTO record_track VALUES (NULL,53,57,0);
INSERT INTO record_track VALUES (NULL,100,14,1);
INSERT INTO record_track VALUES (NULL,95,95,0);
INSERT INTO record_track VALUES (NULL,68,96,0);
INSERT INTO record_track VALUES (NULL,69,12,1);
INSERT INTO record_track VALUES (NULL,11,33,1);
INSERT INTO record_track VALUES (NULL,25,34,0);
INSERT INTO record_track VALUES (NULL,27,77,1);
INSERT INTO record_track VALUES (NULL,31,97,1);
INSERT INTO record_track VALUES (NULL,71,98,1);
INSERT INTO record_track VALUES (NULL,31,26,1);
INSERT INTO record_track VALUES (NULL,98,60,0);
INSERT INTO record_track VALUES (NULL,78,5,0);
INSERT INTO record_track VALUES (NULL,32,25,1);
INSERT INTO record_track VALUES (NULL,7,66,1);
INSERT INTO record_track VALUES (NULL,78,61,1);
INSERT INTO record_track VALUES (NULL,41,44,0);
INSERT INTO record_track VALUES (NULL,31,23,0);
INSERT INTO record_track VALUES (NULL,62,50,1);
INSERT INTO record_track VALUES (NULL,67,27,1);
INSERT INTO record_track VALUES (NULL,90,67,0);
INSERT INTO record_track VALUES (NULL,21,59,0);
INSERT INTO record_track VALUES (NULL,11,61,0);
INSERT INTO record_track VALUES (NULL,96,70,1);
INSERT INTO record_track VALUES (NULL,43,71,0);
INSERT INTO record_track VALUES (NULL,45,16,1);
INSERT INTO record_track VALUES (NULL,34,38,1);
INSERT INTO record_track VALUES (NULL,72,46,0);
INSERT INTO record_track VALUES (NULL,52,92,1);
INSERT INTO record_track VALUES (NULL,99,23,1);
INSERT INTO record_track VALUES (NULL,90,71,1);
INSERT INTO record_track VALUES (NULL,26,12,1);
INSERT INTO record_track VALUES (NULL,82,51,0);
INSERT INTO record_track VALUES (NULL,80,15,1);
INSERT INTO record_track VALUES (NULL,17,64,1);
INSERT INTO record_track VALUES (NULL,87,36,1);
INSERT INTO record_track VALUES (NULL,27,98,1);
INSERT INTO record_track VALUES (NULL,94,53,1);
INSERT INTO record_track VALUES (NULL,4,88,0);
INSERT INTO record_track VALUES (NULL,66,35,0);
INSERT INTO record_track VALUES (NULL,12,71,1);
INSERT INTO record_track VALUES (NULL,9,25,1);
INSERT INTO record_track VALUES (NULL,76,86,1);
INSERT INTO record_track VALUES (NULL,56,47,0);
INSERT INTO record_track VALUES (NULL,67,40,1);
INSERT INTO record_track VALUES (NULL,27,64,1);
INSERT INTO record_track VALUES (NULL,51,93,1);
INSERT INTO record_track VALUES (NULL,62,4,1);
INSERT INTO record_track VALUES (NULL,39,50,0);
INSERT INTO record_track VALUES (NULL,72,59,0);
INSERT INTO record_track VALUES (NULL,41,14,0);
INSERT INTO record_track VALUES (NULL,76,18,0);
INSERT INTO record_track VALUES (NULL,70,60,1);
INSERT INTO record_track VALUES (NULL,40,19,0);
INSERT INTO record_track VALUES (NULL,63,73,1);
INSERT INTO record_track VALUES (NULL,33,0,0);
INSERT INTO record_track VALUES (NULL,78,14,0);
INSERT INTO record_track VALUES (NULL,40,44,0);
INSERT INTO record_track VALUES (NULL,42,20,0);
INSERT INTO record_track VALUES (NULL,79,44,1);
INSERT INTO record_track VALUES (NULL,98,62,0);
INSERT INTO record_track VALUES (NULL,69,30,1);
INSERT INTO record_track VALUES (NULL,65,47,0);
INSERT INTO record_track VALUES (NULL,36,22,0);
INSERT INTO record_track VALUES (NULL,89,73,0);
INSERT INTO record_track VALUES (NULL,92,2,0);
INSERT INTO record_track VALUES (NULL,3,3,0);
INSERT INTO record_track VALUES (NULL,79,40,0);
INSERT INTO record_track VALUES (NULL,16,28,0);
INSERT INTO record_track VALUES (NULL,48,49,0);
INSERT INTO record_track VALUES (NULL,13,36,1);
INSERT INTO record_track VALUES (NULL,74,35,1);
INSERT INTO record_track VALUES (NULL,16,69,0);
INSERT INTO record_track VALUES (NULL,40,61,1);
INSERT INTO record_track VALUES (NULL,16,50,0);
INSERT INTO record_track VALUES (NULL,100,91,0);
INSERT INTO record_track VALUES (NULL,97,4,0);
INSERT INTO record_track VALUES (NULL,57,24,1);
INSERT INTO record_track VALUES (NULL,7,38,1);
INSERT INTO record_track VALUES (NULL,50,15,1);
INSERT INTO record_track VALUES (NULL,15,19,1);
INSERT INTO record_track VALUES (NULL,62,37,1);
INSERT INTO record_track VALUES (NULL,76,50,0);
INSERT INTO record_track VALUES (NULL,66,77,1);
INSERT INTO record_track VALUES (NULL,59,30,0);
INSERT INTO record_track VALUES (NULL,68,17,1);
INSERT INTO record_track VALUES (NULL,47,81,1);
INSERT INTO record_track VALUES (NULL,20,15,0);
INSERT INTO record_track VALUES (NULL,74,74,1);
INSERT INTO record_track VALUES (NULL,48,20,1);
INSERT INTO record_track VALUES (NULL,40,22,0);
INSERT INTO record_track VALUES (NULL,13,30,0);
INSERT INTO record_track VALUES (NULL,64,30,1);
INSERT INTO record_track VALUES (NULL,12,81,0);
INSERT INTO record_track VALUES (NULL,15,49,0);
INSERT INTO record_track VALUES (NULL,84,23,0);
INSERT INTO record_track VALUES (NULL,98,9,0);
INSERT INTO record_track VALUES (NULL,12,89,0);
INSERT INTO record_track VALUES (NULL,72,52,0);
INSERT INTO record_track VALUES (NULL,70,50,0);
INSERT INTO record_track VALUES (NULL,63,94,0);
INSERT INTO record_track VALUES (NULL,83,20,1);
INSERT INTO record_track VALUES (NULL,26,63,1);
INSERT INTO record_track VALUES (NULL,94,30,1);
INSERT INTO record_track VALUES (NULL,63,52,1);
INSERT INTO record_track VALUES (NULL,97,45,1);
INSERT INTO record_track VALUES (NULL,64,40,0);
INSERT INTO record_track VALUES (NULL,87,86,1);
INSERT INTO record_track VALUES (NULL,55,7,1);
INSERT INTO record_track VALUES (NULL,25,73,0);
INSERT INTO record_track VALUES (NULL,78,26,0);
INSERT INTO record_track VALUES (NULL,94,4,1);
INSERT INTO record_track VALUES (NULL,18,77,0);
INSERT INTO record_track VALUES (NULL,76,18,0);
INSERT INTO record_track VALUES (NULL,11,84,0);
INSERT INTO record_track VALUES (NULL,77,82,0);
INSERT INTO record_track VALUES (NULL,39,78,0);
INSERT INTO record_track VALUES (NULL,17,57,1);
INSERT INTO record_track VALUES (NULL,97,35,0);
INSERT INTO record_track VALUES (NULL,49,77,1);
INSERT INTO record_track VALUES (NULL,0,11,1);
INSERT INTO record_track VALUES (NULL,44,72,1);
INSERT INTO record_track VALUES (NULL,43,39,0);
INSERT INTO record_track VALUES (NULL,70,13,1);
INSERT INTO record_track VALUES (NULL,29,59,0);
INSERT INTO record_track VALUES (NULL,83,91,1);
INSERT INTO record_track VALUES (NULL,83,62,0);
INSERT INTO record_track VALUES (NULL,44,67,0);
INSERT INTO record_track VALUES (NULL,15,13,1);
INSERT INTO record_track VALUES (NULL,18,70,1);
INSERT INTO record_track VALUES (NULL,64,20,1);
INSERT INTO record_track VALUES (NULL,49,24,1);
INSERT INTO record_track VALUES (NULL,45,10,1);
INSERT INTO record_track VALUES (NULL,18,96,0);
INSERT INTO record_track VALUES (NULL,34,17,1);
INSERT INTO record_track VALUES (NULL,23,27,1);
INSERT INTO record_track VALUES (NULL,41,0,1);
INSERT INTO record_track VALUES (NULL,61,93,0);
INSERT INTO record_track VALUES (NULL,23,12,1);
INSERT INTO record_track VALUES (NULL,32,25,0);
INSERT INTO record_track VALUES (NULL,49,6,0);
INSERT INTO record_track VALUES (NULL,9,84,1);
INSERT INTO record_track VALUES (NULL,59,26,1);
INSERT INTO record_track VALUES (NULL,76,92,1);
INSERT INTO record_track VALUES (NULL,73,2,0);
INSERT INTO record_track VALUES (NULL,84,0,0);
INSERT INTO record_track VALUES (NULL,57,83,1);
INSERT INTO record_track VALUES (NULL,48,3,0);
INSERT INTO record_track VALUES (NULL,10,70,1);
INSERT INTO record_track VALUES (NULL,45,32,1);
INSERT INTO record_track VALUES (NULL,84,15,1);
INSERT INTO record_track VALUES (NULL,4,14,1);
INSERT INTO record_track VALUES (NULL,39,61,0);
INSERT INTO record_track VALUES (NULL,57,57,0);
INSERT INTO record_track VALUES (NULL,75,82,1);
INSERT INTO record_track VALUES (NULL,5,87,1);
INSERT INTO record_track VALUES (NULL,76,28,1);
INSERT INTO record_track VALUES (NULL,15,66,1);
INSERT INTO record_track VALUES (NULL,1,58,1);
INSERT INTO record_track VALUES (NULL,58,21,1);
INSERT INTO record_track VALUES (NULL,11,4,0);
INSERT INTO record_track VALUES (NULL,93,22,1);
INSERT INTO record_track VALUES (NULL,81,7,1);
INSERT INTO record_track VALUES (NULL,1,10,0);
INSERT INTO record_track VALUES (NULL,71,2,1);
INSERT INTO record_track VALUES (NULL,16,40,1);
INSERT INTO record_track VALUES (NULL,66,94,0);
INSERT INTO record_track VALUES (NULL,27,39,0);
INSERT INTO record_track VALUES (NULL,2,91,1);
INSERT INTO record_track VALUES (NULL,18,44,0);
INSERT INTO record_track VALUES (NULL,46,35,1);
INSERT INTO record_track VALUES (NULL,16,73,1);
INSERT INTO record_track VALUES (NULL,8,54,1);
INSERT INTO record_track VALUES (NULL,60,28,0);
INSERT INTO record_track VALUES (NULL,80,56,1);
INSERT INTO record_track VALUES (NULL,9,82,1);
INSERT INTO record_track VALUES (NULL,30,31,0);
INSERT INTO record_track VALUES (NULL,54,21,0);
INSERT INTO record_track VALUES (NULL,65,86,0);
INSERT INTO record_track VALUES (NULL,34,36,1);
INSERT INTO record_track VALUES (NULL,90,17,1);
INSERT INTO record_track VALUES (NULL,43,14,1);
INSERT INTO record_track VALUES (NULL,28,60,1);
INSERT INTO record_track VALUES (NULL,56,76,1);
INSERT INTO record_track VALUES (NULL,9,94,0);
INSERT INTO record_track VALUES (NULL,38,40,0);
INSERT INTO record_track VALUES (NULL,67,24,1);
INSERT INTO record_track VALUES (NULL,93,45,1);
INSERT INTO record_track VALUES (NULL,56,89,0);
INSERT INTO record_track VALUES (NULL,59,84,1);
INSERT INTO record_track VALUES (NULL,97,48,0);
INSERT INTO record_track VALUES (NULL,29,48,1);
INSERT INTO record_track VALUES (NULL,88,11,1);
INSERT INTO record_track VALUES (NULL,43,54,1);
INSERT INTO record_track VALUES (NULL,66,69,1);
INSERT INTO record_track VALUES (NULL,34,28,1);
INSERT INTO record_track VALUES (NULL,52,88,1);
INSERT INTO record_track VALUES (NULL,68,16,0);
INSERT INTO record_track VALUES (NULL,47,21,1);
INSERT INTO record_track VALUES (NULL,42,19,0);
INSERT INTO record_track VALUES (NULL,22,30,0);
INSERT INTO record_track VALUES (NULL,37,75,1);
INSERT INTO record_track VALUES (NULL,11,18,1);
INSERT INTO record_track VALUES (NULL,33,35,0);
INSERT INTO record_track VALUES (NULL,11,89,0);
INSERT INTO record_track VALUES (NULL,99,29,0);
INSERT INTO record_track VALUES (NULL,94,4,0);
INSERT INTO record_track VALUES (NULL,94,16,0);
INSERT INTO record_track VALUES (NULL,12,76,0);
INSERT INTO record_track VALUES (NULL,30,81,0);
INSERT INTO record_track VALUES (NULL,36,65,0);
INSERT INTO record_track VALUES (NULL,74,84,1);
INSERT INTO record_track VALUES (NULL,79,25,0);
INSERT INTO record_track VALUES (NULL,2,62,1);
INSERT INTO record_track VALUES (NULL,34,10,1);
INSERT INTO record_track VALUES (NULL,46,93,1);
INSERT INTO record_track VALUES (NULL,9,53,0);
INSERT INTO record_track VALUES (NULL,82,0,0);
INSERT INTO record_track VALUES (NULL,22,33,1);
INSERT INTO record_track VALUES (NULL,99,62,1);
INSERT INTO record_track VALUES (NULL,43,39,0);
INSERT INTO record_track VALUES (NULL,78,30,1);
INSERT INTO record_track VALUES (NULL,19,80,1);
INSERT INTO record_track VALUES (NULL,63,5,0);
INSERT INTO record_track VALUES (NULL,67,24,1);
INSERT INTO record_track VALUES (NULL,81,93,1);
INSERT INTO record_track VALUES (NULL,41,35,0);
INSERT INTO record_track VALUES (NULL,68,4,0);
INSERT INTO record_track VALUES (NULL,19,26,1);
INSERT INTO record_track VALUES (NULL,29,9,0);
INSERT INTO record_track VALUES (NULL,92,33,0);
INSERT INTO record_track VALUES (NULL,51,17,0);
INSERT INTO record_track VALUES (NULL,46,13,1);
INSERT INTO record_track VALUES (NULL,21,81,0);
INSERT INTO record_track VALUES (NULL,90,56,0);
INSERT INTO record_track VALUES (NULL,54,14,0);
INSERT INTO record_track VALUES (NULL,63,72,1);
INSERT INTO record_track VALUES (NULL,83,3,1);
INSERT INTO record_track VALUES (NULL,17,27,0);
INSERT INTO record_track VALUES (NULL,39,35,0);
INSERT INTO record_track VALUES (NULL,13,30,0);
INSERT INTO record_track VALUES (NULL,24,33,1);
INSERT INTO record_track VALUES (NULL,74,71,0);
INSERT INTO record_track VALUES (NULL,51,47,1);
INSERT INTO record_track VALUES (NULL,5,64,0);
INSERT INTO record_track VALUES (NULL,12,10,0);
INSERT INTO record_track VALUES (NULL,58,28,0);
INSERT INTO record_track VALUES (NULL,70,33,1);
INSERT INTO record_track VALUES (NULL,86,67,0);
INSERT INTO record_track VALUES (NULL,82,21,0);
INSERT INTO record_track VALUES (NULL,66,73,0);
INSERT INTO record_track VALUES (NULL,58,86,0);
INSERT INTO record_track VALUES (NULL,39,2,0);
INSERT INTO record_track VALUES (NULL,17,40,0);
INSERT INTO record_track VALUES (NULL,55,90,1);
INSERT INTO record_track VALUES (NULL,82,33,0);
INSERT INTO record_track VALUES (NULL,10,74,0);
INSERT INTO record_track VALUES (NULL,68,32,1);
INSERT INTO record_track VALUES (NULL,46,56,0);
INSERT INTO record_track VALUES (NULL,48,93,1);
INSERT INTO record_track VALUES (NULL,23,39,0);
INSERT INTO record_track VALUES (NULL,27,32,1);
INSERT INTO record_track VALUES (NULL,50,12,1);
INSERT INTO record_track VALUES (NULL,40,60,0);
INSERT INTO record_track VALUES (NULL,42,64,1);
INSERT INTO record_track VALUES (NULL,16,56,1);
INSERT INTO record_track VALUES (NULL,27,76,1);
INSERT INTO record_track VALUES (NULL,98,80,0);
INSERT INTO record_track VALUES (NULL,8,3,0);
INSERT INTO record_track VALUES (NULL,62,54,0);
INSERT INTO record_track VALUES (NULL,20,97,1);
INSERT INTO record_track VALUES (NULL,8,58,1);
INSERT INTO record_track VALUES (NULL,52,91,1);
INSERT INTO record_track VALUES (NULL,3,23,1);
INSERT INTO record_track VALUES (NULL,24,20,1);
INSERT INTO record_track VALUES (NULL,67,48,1);
INSERT INTO record_track VALUES (NULL,23,62,0);
INSERT INTO record_track VALUES (NULL,2,8,1);
INSERT INTO record_track VALUES (NULL,4,33,1);
INSERT INTO record_track VALUES (NULL,95,32,1);
INSERT INTO record_track VALUES (NULL,20,67,0);
INSERT INTO record_track VALUES (NULL,20,98,1);
INSERT INTO record_track VALUES (NULL,17,1,0);
INSERT INTO record_track VALUES (NULL,11,90,1);
INSERT INTO record_track VALUES (NULL,46,58,0);
INSERT INTO record_track VALUES (NULL,7,43,1);
INSERT INTO record_track VALUES (NULL,15,41,1);
INSERT INTO record_track VALUES (NULL,83,9,0);
INSERT INTO record_track VALUES (NULL,4,64,1);
INSERT INTO record_track VALUES (NULL,23,93,0);
INSERT INTO record_track VALUES (NULL,65,93,0);
INSERT INTO record_track VALUES (NULL,56,68,1);
INSERT INTO record_track VALUES (NULL,82,15,1);
INSERT INTO record_track VALUES (NULL,91,7,1);
INSERT INTO record_track VALUES (NULL,69,28,0);
INSERT INTO record_track VALUES (NULL,96,43,0);
INSERT INTO record_track VALUES (NULL,59,83,1);
INSERT INTO record_track VALUES (NULL,1,56,0);
INSERT INTO record_track VALUES (NULL,41,43,1);
INSERT INTO record_track VALUES (NULL,88,17,0);
INSERT INTO record_track VALUES (NULL,52,57,0);
INSERT INTO record_track VALUES (NULL,47,88,0);
INSERT INTO record_track VALUES (NULL,98,6,1);
INSERT INTO record_track VALUES (NULL,52,42,0);
INSERT INTO record_track VALUES (NULL,23,88,1);
INSERT INTO record_track VALUES (NULL,18,74,1);
INSERT INTO record_track VALUES (NULL,63,83,0);
INSERT INTO record_track VALUES (NULL,38,95,0);
INSERT INTO record_track VALUES (NULL,55,85,1);
INSERT INTO record_track VALUES (NULL,67,43,1);
INSERT INTO record_track VALUES (NULL,65,74,1);
INSERT INTO record_track VALUES (NULL,68,25,1);
INSERT INTO record_track VALUES (NULL,36,78,1);
INSERT INTO record_track VALUES (NULL,28,15,1);
INSERT INTO record_track VALUES (NULL,18,4,0);
INSERT INTO record_track VALUES (NULL,99,12,0);
INSERT INTO record_track VALUES (NULL,48,70,0);
INSERT INTO record_track VALUES (NULL,28,91,0);
INSERT INTO record_track VALUES (NULL,25,24,0);
INSERT INTO record_track VALUES (NULL,17,78,0);
INSERT INTO record_track VALUES (NULL,27,51,1);
INSERT INTO record_track VALUES (NULL,20,70,1);
INSERT INTO record_track VALUES (NULL,62,63,1);
INSERT INTO record_track VALUES (NULL,17,18,1);
INSERT INTO record_track VALUES (NULL,43,3,1);
INSERT INTO record_track VALUES (NULL,21,35,0);
INSERT INTO record_track VALUES (NULL,80,52,0);
INSERT INTO record_track VALUES (NULL,58,36,1);
INSERT INTO record_track VALUES (NULL,47,32,0);
INSERT INTO record_track VALUES (NULL,64,52,1);
INSERT INTO record_track VALUES (NULL,10,41,1);
INSERT INTO record_track VALUES (NULL,9,65,0);
INSERT INTO record_track VALUES (NULL,7,71,0);
INSERT INTO record_track VALUES (NULL,86,38,0);
INSERT INTO record_track VALUES (NULL,72,37,0);
INSERT INTO record_track VALUES (NULL,59,40,0);
INSERT INTO record_track VALUES (NULL,12,61,0);
INSERT INTO record_track VALUES (NULL,12,52,1);
INSERT INTO record_track VALUES (NULL,69,6,1);
INSERT INTO record_track VALUES (NULL,24,98,0);
INSERT INTO record_track VALUES (NULL,1,9,0);
INSERT INTO record_track VALUES (NULL,63,6,1);
INSERT INTO record_track VALUES (NULL,26,90,0);
INSERT INTO record_track VALUES (NULL,94,67,0);
INSERT INTO record_track VALUES (NULL,14,72,1);
INSERT INTO record_track VALUES (NULL,96,23,1);
INSERT INTO record_track VALUES (NULL,63,66,1);
INSERT INTO record_track VALUES (NULL,61,17,1);
INSERT INTO record_track VALUES (NULL,44,37,0);
INSERT INTO record_track VALUES (NULL,55,25,0);
INSERT INTO record_track VALUES (NULL,68,18,0);
INSERT INTO record_track VALUES (NULL,18,52,1);
INSERT INTO record_track VALUES (NULL,3,98,0);
INSERT INTO record_track VALUES (NULL,46,51,1);
INSERT INTO record_track VALUES (NULL,60,7,1);
INSERT INTO record_track VALUES (NULL,46,83,1);
INSERT INTO record_track VALUES (NULL,60,27,1);
INSERT INTO record_track VALUES (NULL,5,82,1);
INSERT INTO record_track VALUES (NULL,56,73,0);
INSERT INTO record_track VALUES (NULL,49,63,1);
INSERT INTO record_track VALUES (NULL,25,11,1);
INSERT INTO record_track VALUES (NULL,81,69,1);
INSERT INTO record_track VALUES (NULL,97,17,1);
INSERT INTO record_track VALUES (NULL,22,13,0);
INSERT INTO record_track VALUES (NULL,69,54,1);
INSERT INTO record_track VALUES (NULL,63,90,1);
INSERT INTO record_track VALUES (NULL,58,18,1);
INSERT INTO record_track VALUES (NULL,35,9,0);
INSERT INTO record_track VALUES (NULL,95,72,0);
INSERT INTO record_track VALUES (NULL,63,24,0);
INSERT INTO record_track VALUES (NULL,46,42,0);
INSERT INTO record_track VALUES (NULL,84,54,1);
INSERT INTO record_track VALUES (NULL,40,38,0);
INSERT INTO record_track VALUES (NULL,46,92,1);
INSERT INTO record_track VALUES (NULL,35,65,0);
INSERT INTO record_track VALUES (NULL,41,8,1);
INSERT INTO record_track VALUES (NULL,82,56,0);
INSERT INTO record_track VALUES (NULL,2,51,1);
INSERT INTO record_track VALUES (NULL,71,97,1);
INSERT INTO record_track VALUES (NULL,2,18,0);
INSERT INTO record_track VALUES (NULL,10,13,0);
INSERT INTO record_track VALUES (NULL,11,9,0);
INSERT INTO record_track VALUES (NULL,13,88,1);
INSERT INTO record_track VALUES (NULL,91,90,0);
INSERT INTO record_track VALUES (NULL,13,29,1);
INSERT INTO record_track VALUES (NULL,25,90,1);
INSERT INTO record_track VALUES (NULL,19,10,0);
INSERT INTO record_track VALUES (NULL,26,37,1);
INSERT INTO record_track VALUES (NULL,7,55,0);
INSERT INTO record_track VALUES (NULL,63,84,1);
INSERT INTO record_track VALUES (NULL,30,82,0);
INSERT INTO record_track VALUES (NULL,46,0,0);
INSERT INTO record_track VALUES (NULL,12,44,0);
INSERT INTO record_track VALUES (NULL,31,76,0);
INSERT INTO record_track VALUES (NULL,53,62,0);
INSERT INTO record_track VALUES (NULL,55,29,0);
INSERT INTO record_track VALUES (NULL,57,39,0);
INSERT INTO record_track VALUES (NULL,18,58,0);
INSERT INTO record_track VALUES (NULL,4,17,0);
INSERT INTO record_track VALUES (NULL,81,30,0);
INSERT INTO record_track VALUES (NULL,45,70,0);
INSERT INTO record_track VALUES (NULL,32,14,0);
INSERT INTO record_track VALUES (NULL,58,76,1);
INSERT INTO record_track VALUES (NULL,35,77,1);
INSERT INTO record_track VALUES (NULL,34,10,0);
INSERT INTO record_track VALUES (NULL,30,78,1);
INSERT INTO record_track VALUES (NULL,7,94,0);
INSERT INTO record_track VALUES (NULL,77,68,1);
INSERT INTO record_track VALUES (NULL,87,65,0);
INSERT INTO record_track VALUES (NULL,87,67,0);
INSERT INTO record_track VALUES (NULL,50,42,0);
INSERT INTO record_track VALUES (NULL,49,85,1);
INSERT INTO record_track VALUES (NULL,24,30,0);
INSERT INTO record_track VALUES (NULL,94,74,0);
INSERT INTO record_track VALUES (NULL,26,9,1);
INSERT INTO record_track VALUES (NULL,62,89,1);
INSERT INTO record_track VALUES (NULL,9,7,1);
INSERT INTO record_track VALUES (NULL,1,36,0);
INSERT INTO record_track VALUES (NULL,62,11,0);
INSERT INTO record_track VALUES (NULL,61,58,1);
INSERT INTO record_track VALUES (NULL,40,26,1);
INSERT INTO record_track VALUES (NULL,54,44,1);
INSERT INTO record_track VALUES (NULL,81,52,0);
INSERT INTO record_track VALUES (NULL,31,20,1);
INSERT INTO record_track VALUES (NULL,14,40,1);
INSERT INTO record_track VALUES (NULL,58,25,1);
INSERT INTO record_track VALUES (NULL,33,76,0);
INSERT INTO record_track VALUES (NULL,38,65,1);
INSERT INTO record_track VALUES (NULL,68,30,0);
INSERT INTO record_track VALUES (NULL,23,56,1);
INSERT INTO record_track VALUES (NULL,91,69,0);
INSERT INTO record_track VALUES (NULL,49,86,0);
INSERT INTO record_track VALUES (NULL,11,30,0);
INSERT INTO record_track VALUES (NULL,49,77,1);
INSERT INTO record_track VALUES (NULL,67,76,0);
INSERT INTO record_track VALUES (NULL,42,65,1);
INSERT INTO record_track VALUES (NULL,48,35,1);
INSERT INTO record_track VALUES (NULL,11,67,0);
INSERT INTO record_track VALUES (NULL,54,54,1);
INSERT INTO record_track VALUES (NULL,95,23,1);
INSERT INTO record_track VALUES (NULL,78,8,1);
INSERT INTO record_track VALUES (NULL,94,5,1);
INSERT INTO record_track VALUES (NULL,99,57,1);
INSERT INTO record_track VALUES (NULL,90,78,0);
INSERT INTO record_track VALUES (NULL,63,81,1);
INSERT INTO record_track VALUES (NULL,99,67,0);
INSERT INTO record_track VALUES (NULL,73,78,0);
INSERT INTO record_track VALUES (NULL,34,71,0);
INSERT INTO record_track VALUES (NULL,92,31,1);
INSERT INTO record_track VALUES (NULL,59,51,1);
INSERT INTO record_track VALUES (NULL,66,45,0);
INSERT INTO record_track VALUES (NULL,69,27,1);
INSERT INTO record_track VALUES (NULL,92,36,1);
INSERT INTO record_track VALUES (NULL,82,65,0);
INSERT INTO record_track VALUES (NULL,6,69,0);
INSERT INTO record_track VALUES (NULL,9,66,0);
INSERT INTO record_track VALUES (NULL,38,50,1);
INSERT INTO record_track VALUES (NULL,8,28,1);
INSERT INTO record_track VALUES (NULL,58,40,0);
INSERT INTO record_track VALUES (NULL,46,30,0);
INSERT INTO record_track VALUES (NULL,48,96,1);
INSERT INTO record_track VALUES (NULL,37,27,1);
INSERT INTO record_track VALUES (NULL,85,97,1);
INSERT INTO record_track VALUES (NULL,36,25,1);
INSERT INTO record_track VALUES (NULL,88,29,0);
INSERT INTO record_track VALUES (NULL,9,89,1);
INSERT INTO record_track VALUES (NULL,61,11,1);
INSERT INTO record_track VALUES (NULL,78,43,1);
INSERT INTO record_track VALUES (NULL,8,5,0);
INSERT INTO record_track VALUES (NULL,14,74,1);
INSERT INTO record_track VALUES (NULL,43,32,1);
INSERT INTO record_track VALUES (NULL,14,59,0);
INSERT INTO record_track VALUES (NULL,34,44,0);
INSERT INTO record_track VALUES (NULL,77,12,0);
INSERT INTO record_track VALUES (NULL,66,17,1);
INSERT INTO record_track VALUES (NULL,53,10,0);
INSERT INTO record_track VALUES (NULL,82,92,0);
INSERT INTO record_track VALUES (NULL,44,82,1);
INSERT INTO record_track VALUES (NULL,15,7,0);
INSERT INTO record_track VALUES (NULL,88,58,1);
INSERT INTO record_track VALUES (NULL,81,43,0);
INSERT INTO record_track VALUES (NULL,80,73,0);
INSERT INTO record_track VALUES (NULL,64,61,0);
INSERT INTO record_track VALUES (NULL,100,85,1);
INSERT INTO record_track VALUES (NULL,31,83,0);